### ISSUE TITLE
A minor typo

### ISSUE THREAD

**Issue by NicklasOlsen** [microsoft/Security-101#10]
Hi,

Just spotted this minor typo in the the second last line under data lifecycle.
https://github.com/microsoft/Security-101/blob/main/7.1%20Data%20security%20key%20concepts.md#what-is-data-lifecycle-management

"data cleansing"

**Comment by banreyms** [comment]
@NicklasOlsen what's the typo you're looking at? "data cleansing" is correct. Was there something else?

**Comment by NicklasOlsen** [comment]
That's my bad, I will close the issue 😊.
