### ISSUE TITLE
Table Module 1: Link to 1.5 has in the Filename 1.6 and 1.6 has 1.5

### ISSUE THREAD

**Issue by fschuermeyer** [microsoft/Security-101#29]
**Describe the bug**
In the table of the https://github.com/microsoft/Security-101/blob/main/README.md, the link in section 1.5 has 1.6 in the file name and 1.6 has 1.5 in the file name, I think the order has been changed here, would it make sense to adjust the file names accordingly to reduce confusion?

**Expected behavior**
The expected behaviour would be if I click on the link at 1.5 and have 1.5 in the file name.

**Comment by fhinkel** [comment]
Fixed via https://github.com/microsoft/Security-101/pull/30
