### ISSUE TITLE
Issue at privacy concept

### ISSUE THREAD

**Issue by NicklasOlsen** [microsoft/Security-101#7]
Hi,

I think it's a mistake, but "privacy" stands alone in the end of the sentence when you are talking about privacy as a concept.
I noticed this when reading through "What are authenticity, nonrepudiation, and privacy in the context of cyber security?".

https://github.com/microsoft/Security-101/blob/main/1.1%20The%20CIA%20triad%20and%20other%20key%20concepts.md#what-are-authenticity-nonrepudiation-and-privacy-in-the-context-of-cyber-security

**Comment by banreyms** [comment]
Thank you! Fixed and credited to you for finding it.
