### ISSUE TITLE
Additional reading for zero trust

### ISSUE THREAD

**Issue by NicklasOlsen** [microsoft/Security-101#8]
Hi,

When talking about zero trust, I was wondering if it could be a good idea to add this Microsoft resource to the "further reading".
https://learn.microsoft.com/en-us/security/zero-trust/zero-trust-overview

If the reader is interested in learning more or diving into the process of deploying zero trust in an organization 😊

https://github.com/microsoft/Security-101/blob/main/1.5%20Zero%20trust.md#further-reading

**Comment by banreyms** [comment]
Great suggestion! added.
